apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce      # only one Pod can write at a time (standard for databases)
  resources:
    requests:
      storage: 1Gi       # request 1GB of disk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1            # databases always use replicas: 1 (disk cannot be shared for writes)
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              value: taskflow
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data   # where postgres stores its data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc                 # connects to the PVC above
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP          # only accessible inside the cluster, never exposed externally
